In [1]:
import pandas as pd

In [3]:
data=pd.read_csv(r"C:\Users\Nandani\Downloads\Streaming_Platform_Data.csv")

Q1. Basic Inspection
Load dataset
Display shape
Check data types
Show missing values count

In [4]:
data.shape

(1500, 13)

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Show_ID            1500 non-null   int64
 1   Title              1500 non-null   object
 2   Genre              1189 non-null   object
 3   Release_Year       1295 non-null   float64
 4   Platform           1500 non-null   object
 5   Director           1132 non-null   object
 6   Country            1500 non-null   object
 7   Duration_Minutes   1500 non-null   int64
 8   IMDB_Rating        1500 non-null   float64
 9   Views_Millions     1490 non-null   float64
 10  Subscription_Type  1500 non-null   object
 11  Revenue_Million    1500 non-null   float64
 12  Region             1015 non-null   object
dtypes: float64(4), int64(2), object(7)
memory usage: 152.5+ KB

In [9]:
data.isnull().sum()

Show_ID                0
Title                  0
Genre                311
Release_Year         205
Platform               0
Director             368
Country                0
Duration_Minutes       0
IMDB_Rating            0
Views_Millions        10
Subscription_Type      0
Revenue_Million        0
Region               485
dtype: int64

Q2. Release Year Cleaning
Fill missing Release_Year using suitable central tendency
Convert column to integer
Create new column Release_Decade

In [10]:
data.head(1)

,Show_ID,Title,Genre,Release_Year,Platform,Director,Country,Duration_Minutes,IMDB_Rating,Views_Millions,Subscription_Type,Revenue_Million,Region
0,1,Show_1,Thriller,2010.0,Netflix,NaN,Canada,67,4.3,14.7,Free,133.3,NaN

In [12]:
data["Release_Year"].median()

2010.0

In [13]:
data["Release_Year"]=data["Release_Year"].fillna(data["Release_Year"].median())

In [14]:
data["Release_Year"]=data["Release_Year"].astype(int)

In [15]:
data["Release_Decade"]=data["Release_Year"]/10*10

In [16]:
data.head(1)

,Show_ID,Title,Genre,Release_Year,Platform,Director,Country,Duration_Minutes,IMDB_Rating,Views_Millions,Subscription_Type,Revenue_Million,Region,Release_Decade
0,1,Show_1,Thriller,2010,Netflix,NaN,Canada,67,4.3,14.7,Free,133.3,NaN,2010.0

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Show_ID            1500 non-null   int64
 1   Title              1500 non-null   object
 2   Genre              1189 non-null   object
 3   Release_Year       1500 non-null   int64
 4   Platform           1500 non-null   object
 5   Director           1132 non-null   object
 6   Country            1500 non-null   object
 7   Duration_Minutes   1500 non-null   int64
 8   IMDB_Rating        1500 non-null   float64
 9   Views_Millions     1490 non-null   float64
 10  Subscription_Type  1500 non-null   object
 11  Revenue_Million    1500 non-null   float64
 12  Region             1015 non-null   object
 13  Release_Decade     1500 non-null   float64
dtypes: float64(4), int64(3), object(7)
memory usage: 164.2+ KB

In [18]:
data["Release_Decade"]=data["Release_Decade"].astype(int)

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Show_ID            1500 non-null   int64
 1   Title              1500 non-null   object
 2   Genre              1189 non-null   object
 3   Release_Year       1500 non-null   int64
 4   Platform           1500 non-null   object
 5   Director           1132 non-null   object
 6   Country            1500 non-null   object
 7   Duration_Minutes   1500 non-null   int64
 8   IMDB_Rating        1500 non-null   float64
 9   Views_Millions     1490 non-null   float64
 10  Subscription_Type  1500 non-null   object
 11  Revenue_Million    1500 non-null   float64
 12  Region             1015 non-null   object
 13  Release_Decade     1500 non-null   int64
dtypes: float64(3), int64(4), object(7)
memory usage: 164.2+ KB

Q3. Revenue Cleaning
Identify negative values in Revenue_Million
Replace them using median
Show summary statistics before & afte

In [20]:
data["Revenue_Million"].unique()

array([133.3, 102.5, 123.7, 117.6, 263.1, 204.3,  68.7, 175.4, 121.7,
        26.6, 220.1, 144.5, 295.5, 279.9, -27.6, -45.4, 177.9,  95.8,
       226.7, 143.7, 263.9, 141.1, 183.3, 286.4,  50.6, 287.6,  58.3,
       -41.9, 260.5,  47.5, -38. , 113.5,  99.1, 189. , 246.3, 143.3,
       162.2, 180.1, 267.7, 290.8, 234.2,  24.8, 222.1, 137.3, 201. ,
       106.8, 281.5,  48.7, 208.9, 215.7,  34. ,  61.8, 128.6, -10.3,
       153.8,  92.7, -10.2, 269.7, 241.9,  63.2,  84.8, 245.6, 110.8,
        88.2, 118.3,   3.5, -11.1,   1.4, -44.4, 267.1, 161.9, 126.7,
        98.6, 229.9, -27.9,   9.6,  88.1,  75.4, 138.3,  95.5, 196.7,
        -9. , 168.2, -39.2, 177. ,  27.4, 283.7, 252.2, 241.3,  40.5,
        72.4,  25.1,  68.6, -41.4,  40.9, 119.3, 232.2, 166.1, 238.3,
        76.4, 293.4, 178.8, 124.9, 132.7, -38.9, -19.5, -37. , 139.9,
        10.1, 125.1,  48.8,  -7.7, 206.9,  81.7,  69.5, 183. , 119.8,
        48.6,  96.3,  82.5,  18.9, 124.8, -47.1, 266. , -45.8, 172.8,
        96.2,   7.2, 241.2, 233.5, 129.4, 128.2, 286.3, -14.2, 122.4,
        57.1, 217.5, -41.1, 292.5, 108.3, 211.9, 173.2, 266.5,  70.9,
       265.2, 169.6, 156.6, 276. , 232.1, 157.9, 216.2,  41.4, 295.1,
       141.3, 118.2, 185.9, 100.7,   6.1,  72.9, -27.7, 299.6, 210. ,
       -47.9, -40.8,   5.2, 129. , 195.3,  38.6, 197.8, 264.6, -10.8,
       -25.5,  14.7, 127.1, 218.8,  37.1, 213.5, 207.8, 275.9,  31.6,
         1.9, 190.3, 150.1,  89.6, 156. ,  74.7, 274.5, 211.8, 224.5,
       241.5,  52.6, 104.3,  24.7, 258.6, 292.1,   4.4, 176.9])

In [21]:
med=data["Revenue_Million"].median()

In [22]:
data.loc[data["Revenue_Million"] < 0, "Revenue_Million"] = med

In [23]:
data["Revenue_Million"].unique()

array([133.3, 102.5, 123.7, 117.6, 263.1, 204.3,  68.7, 175.4, 121.7,
        26.6, 220.1, 144.5, 295.5, 279.9, 126.7, 177.9,  95.8, 226.7,
       143.7, 263.9, 141.1, 183.3, 286.4,  50.6, 287.6,  58.3, 260.5,
        47.5, 113.5,  99.1, 189. , 246.3, 143.3, 162.2, 180.1, 267.7,
       290.8, 234.2,  24.8, 222.1, 137.3, 201. , 106.8, 281.5,  48.7,
       208.9, 215.7,  34. ,  61.8, 128.6, 153.8,  92.7, 269.7, 241.9,
        63.2,  84.8, 245.6, 110.8,  88.2, 118.3,   3.5,   1.4, 267.1,
       161.9,  98.6, 229.9,   9.6,  88.1,  75.4, 138.3,  95.5, 196.7,
       168.2, 177. ,  27.4, 283.7, 252.2, 241.3,  40.5,  72.4,  25.1,
        68.6,  40.9, 119.3, 232.2, 166.1, 238.3,  76.4, 293.4, 178.8,
       124.9, 132.7, 139.9,  10.1, 125.1,  48.8, 206.9,  81.7,  69.5,
       183. , 119.8,  48.6,  96.3,  82.5,  18.9, 124.8, 266. , 172.8,
        96.2,   7.2, 241.2, 233.5, 129.4, 128.2, 286.3, 122.4,  57.1,
       217.5, 292.5, 108.3, 211.9, 173.2, 266.5,  70.9, 265.2, 169.6,
       156.6, 276. , 232.1, 157.9, 216.2,  41.4, 295.1, 141.3, 118.2,
       185.9, 100.7,   6.1,  72.9, 299.6, 210. ,   5.2, 129. , 195.3,
        38.6, 197.8, 264.6,  14.7, 127.1, 218.8,  37.1, 213.5, 207.8,
       275.9,  31.6,   1.9, 190.3, 150.1,  89.6, 156. ,  74.7, 274.5,
       211.8, 224.5, 241.5,  52.6, 104.3,  24.7, 258.6, 292.1,   4.4,
       176.9])

Q4. Views Cleaning
Handle missing values in Views_Millions
Explain why you chose mean/median

In [24]:
data["Views_Millions"].unique()

array([14.7, 74.2, 71.5, 80.1, 16.2, 44. , 55.7, 37.9, 54.8, 57.8, 67.3,
       52.7, 28.5,  9.7, 52. , 23.2, 75.7, 24. , 35.5, 13.1, 29.1, 30.9,
       94. , 15.8, 37.1, 33.1, 37.8, 47.7, 17.4, 40.4, 81.7, 18.1, 27.7,
       54.7, 21.3, 41.5, 65.7, 86.2, 36.5, 44.7, 39.8, 56.4, 13.4, 65.2,
       28.4, 70.1, 17.8, 90.1, 73.9, 17.3, 90.4, 19.4, 59.4, 87.6, 48.1,
       75.9, 86.6, 17.5, 30.4, 43.6, 87.2, 61.7,  6.5, 90. , 70.8, 11. ,
       34.3, 77.6, 34.4, 60.8, 28.9, 40.3, 70.9, 55.1, 51.1, 76.9, 76.2,
        nan, 56. , 33.7, 27.2, 60.3, 87.1, 91.2, 47. , 44.1, 68.2, 16.1,
       82.7, 89.9, 80.4, 92.5, 21.9,  8.5])

In [25]:
data["Views_Millions"].mean()

np.float64(50.42704697986577)

In [26]:
data["Views_Millions"].median()

48.1

In [27]:
data["Views_Millions"]=data["Views_Millions"].fillna(data["Views_Millions"].median())

Q5. Genre Standardization
Remove leading/trailing spaces
Convert to Title Case
Fill remaining null values:
50% Action
50% Drama

In [28]:
data["Genre"]=data["Genre"].str.strip().str.title()

In [29]:
data["Genre"].isnull().sum()

np.int64(311)

In [32]:
311/2

155.5

In [33]:
data["Genre"]=data["Genre"].fillna("Action",limit=155)

In [34]:
data["Genre"]=data["Genre"].fillna("Drama",limit=155)

In [35]:
data["Genre"].isnull().sum()

np.int64(1)

In [36]:
data["Genre"].value_counts()

Genre
Action      471
Drama       449
Comedy      293
Thriller    286
Name: count, dtype: int64

In [37]:
data["Genre"]=data["Genre"].fillna("Drama")

In [38]:
data["Genre"].isnull().sum()

np.int64(0)

Q6. Director Handling
Replace missing Director with "Unknown"
Count how many Unknown

In [40]:
data["Director"].isnull().sum()

np.int64(368)

In [41]:
data["Director"]=data["Director"].fillna("Unknown")

In [49]:
data["Director"].value_counts()

Director
Raj Mehta      388
John Smith     380
Unknown        368
Emma Watson    364
Name: count, dtype: int64

Q7. Region Sequential Filling
Fill missing Region:
First 200 → Asia
Next 200 → Europe
Remaining → North America

In [43]:
data["Region"].isnull().sum()

np.int64(485)

In [44]:
data["Region"]=data["Region"].fillna("Asia",limit = 200)

In [45]:
data["Region"]=data["Region"].fillna("Europe",limit = 200)

In [46]:
data["Region"]=data["Region"].fillna("North America")

In [47]:
data["Region"].isnull().sum()

np.int64(0)

Q8. Feature Engineering
Create:
Revenue_Category
<50 → Low
50–150 → Medium
150 → High
Log_Revenue
Views_Revenue_Ratio

In [51]:
def Revenue_Category(x):
    if x < 50:
        return "Low"
    elif  x < 150:
        return "Medium"
    else :
        return "High"

data["Revenue_Category"]=data["Revenue_Million"].apply(Revenue_Category)

In [52]:
data["Revenue_Category"]

0       Medium
1       Medium
2       Medium
3       Medium
4       Medium
         ...
1495    Medium
1496       Low
1497      High
1498      High
1499       Low
Name: Revenue_Category, Length: 1500, dtype: object

In [50]:
data["Revenue_Million"].unique()

array([133.3, 102.5, 123.7, 117.6, 263.1, 204.3,  68.7, 175.4, 121.7,
        26.6, 220.1, 144.5, 295.5, 279.9, 126.7, 177.9,  95.8, 226.7,
       143.7, 263.9, 141.1, 183.3, 286.4,  50.6, 287.6,  58.3, 260.5,
        47.5, 113.5,  99.1, 189. , 246.3, 143.3, 162.2, 180.1, 267.7,
       290.8, 234.2,  24.8, 222.1, 137.3, 201. , 106.8, 281.5,  48.7,
       208.9, 215.7,  34. ,  61.8, 128.6, 153.8,  92.7, 269.7, 241.9,
        63.2,  84.8, 245.6, 110.8,  88.2, 118.3,   3.5,   1.4, 267.1,
       161.9,  98.6, 229.9,   9.6,  88.1,  75.4, 138.3,  95.5, 196.7,
       168.2, 177. ,  27.4, 283.7, 252.2, 241.3,  40.5,  72.4,  25.1,
        68.6,  40.9, 119.3, 232.2, 166.1, 238.3,  76.4, 293.4, 178.8,
       124.9, 132.7, 139.9,  10.1, 125.1,  48.8, 206.9,  81.7,  69.5,
       183. , 119.8,  48.6,  96.3,  82.5,  18.9, 124.8, 266. , 172.8,
        96.2,   7.2, 241.2, 233.5, 129.4, 128.2, 286.3, 122.4,  57.1,
       217.5, 292.5, 108.3, 211.9, 173.2, 266.5,  70.9, 265.2, 169.6,
       156.6, 276. , 232.1, 157.9, 216.2,  41.4, 295.1, 141.3, 118.2,
       185.9, 100.7,   6.1,  72.9, 299.6, 210. ,   5.2, 129. , 195.3,
        38.6, 197.8, 264.6,  14.7, 127.1, 218.8,  37.1, 213.5, 207.8,
       275.9,  31.6,   1.9, 190.3, 150.1,  89.6, 156. ,  74.7, 274.5,
       211.8, 224.5, 241.5,  52.6, 104.3,  24.7, 258.6, 292.1,   4.4,
       176.9])

In [53]:
import numpy as np

In [55]:
data["Log_Revenue"]=np.log1p(data["Revenue_Million"])

In [57]:
data["Views_Revenue_Ratio"]=data["Views_Millions"]/data["Revenue_Million"]

Q9. Export Two Files
File 1 → Show_Information.csv
Columns:
Show_ID
Title
Genre
Release_Year
Release_Decade
Platform
Director
Revenue_Category
Region

File 2 → Viewership_Data.csv
Columns:
Show_ID
IMDB_Rating
Duration_Minutes
Views_Millions
Revenue_Million
Log_Revenue
Views_Revenue_Ratio

In [60]:
data[["Show_ID","Title","Genre","Release_Year","Release_Decade","Platform","Director","Revenue_Category","Region"]].to_csv("Show_Information.csv",index=False)

In [62]:
data[["Show_ID","IMDB_Rating","Duration_Minutes","Views_Millions","Revenue_Million","Log_Revenue","Views_Revenue_Ratio"]].to_csv("Viewership_Data.csv",index=False)

In [63]:
data.to_csv("Striming_data_clean.csv",index=False)